name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  libnixstore:
    name: Build and Test libnixstore
    timeout-minutes: 60
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        nixpkgs: [nixos-22.05, nixos-unstable]

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:${{ matrix.nixpkgs }}

      - name: nix-shell (for ${{ matrix.nixpkgs }}) and cargo test
        run: |
          # Would be great if we could specify pkg.hello here or so,
          # rather than picking the first in buildInputs
          nix-shell --run 'TEST_NIXPKG=$(echo $buildInputs | cut -f 1 -d" ") cargo test -p libnixstore'

  integration:
    name: Build and Test Harmonia
    timeout-minutes: 60
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        nixpkgs: [nixos-22.05, nixos-unstable]

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:${{ matrix.nixpkgs }}
          extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"

      - name: nix-build (for ${{ matrix.nixpkgs }})
        run: nix-build -E 'with import <nixpkgs> {}; callPackage ./test.nix {nixpkgs = pkgs;}'
